# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    twilio.sid: '%env(TWILIO_SID)%'
    twilio.token: '%env(TWILIO_TOKEN)%'
    twilio.from: '%env(TWILIO_FROM)%'
    app.project_name: 'technologia !!'
    app.stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true #chat
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TwilioService:
        arguments:
            $sid: '%twilio.sid%'
            $token: '%twilio.token%'
            $from: '%twilio.from%'
    App\Controller\CheckoutController:
        arguments:
            $stripeSecretKey: '%app.stripe_secret_key%'
          
